# Generated by Django 5.2.9 on 2025-12-20 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('site_type', models.CharField(choices=[('OUED', 'Oued'), ('WETLAND', 'Wetland'), ('COAST', 'Coast')], default='OUED', max_length=10)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('runoff_factor', models.FloatField(default=0.5)),
                ('land_risk', models.FloatField(default=0.3)),
            ],
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('horizon_hours', models.IntegerField(default=24)),
                ('water_risk', models.FloatField()),
                ('explain_json', models.JSONField(default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plastic_score', models.FloatField(default=0.0)),
                ('ndvi', models.FloatField(default=0.3)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='core.site')),
            ],
            options={
                'unique_together': {('site', 'date')},
            },
        ),
    ]
