# Generated by Django 5.2.9 on 2025-12-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risksnapshot',
            name='bio_risk',
            field=models.FloatField(default=0.0),
        ),
    ]
